const languageList = [
  ['cmn', 'Chinese'],
  ['spa', 'Spanish'],
  ['eng', 'English'],
  ['rus', 'Russian'],
  ['arb', 'Arabic'],
  ['ben', 'Bengali'],
  ['hin', 'Hindi'],
  ['por', 'Portuguese'],
  ['ind', 'Indonesian'],
  ['jpn', 'Japanese'],
  ['fra', 'French'],
  ['deu', 'German'],
  ['jav', 'Javanese'],
  ['kor', 'Korean'],
  ['tel', 'Telugu'],
  ['vie', 'Vietnamese'],
  ['mar', 'Marathi'],
  ['ita', 'Italian'],
  ['tam', 'Tamil'],
  ['tur', 'Turkish'],
  ['urd', 'Urdu'],
  ['guj', 'Gujarati'],
  ['pol', 'Polish'],
  ['ukr', 'Ukrainian'],
  ['kan', 'Kannada'],
  ['mai', 'Maithili'],
  ['mal', 'Malayalam'],
  ['pes', 'Persian'],
  ['mya', 'Burmese'],
  ['swh', 'Swahili'],
  ['sun', 'Sundanese'],
  ['ron', 'Romanian'],
  ['pan', 'Panjabi'],
  ['bho', 'Bhojpuri'],
  ['amh', 'Amharic'],
  ['hau', 'Hausa'],
  ['fuv', 'Fulfulde'],
  ['bos', 'Bosnian'],
  ['hrv', 'Croatian'],
  ['nld', 'Dutch'],
  ['srp', 'Serbian'],
  ['srp', 'Serbian'],
  ['tha', 'Thai'],
  ['ckb', 'Central Kurdish'],
  ['yor', 'Yoruba'],
  ['uzn', 'Northern Uzbek'],
  ['zlm', 'Malay'],
  ['ibo', 'Igbo'],
  ['npi', 'Nepali'],
  ['ceb', 'Cebuano'],
  ['skr', 'Saraiki'],
  ['tgl', 'Tagalog'],
  ['hun', 'Hungarian'],
  ['azj', 'North Azerbaijani'],
  ['sin', 'Sinhala'],
  ['koi', 'Komi-Permyak'],
  ['ell', 'Modern Greek'],
  ['ces', 'Czech'],
  ['mag', 'Magahi'],
  ['run', 'Rundi'],
  ['bel', 'Belarusian'],
  ['plt', 'Plateau Malagasy']
]

export function getLanguageName(lang) {
  const language = languageList.find(([code]) => code === lang);
  return language ? language[1] : lang;
}